os: linux
language: c

env:
   global:
      - OS_TESTED_UBUNTU="ubuntu19.04"

services:
   - docker

before_install:
   - docker build -t ${OS_TESTED_UBUNTU} -f .travis-dockerfiles/Dockerfile.${OS_TESTED_UBUNTU} .
   - docker images

jobs:
  include:
   - name: "celadon_64 (GCC)"
     env: EVMM_BUILD_TARGET="-e TRUSTY_REF_TARGET=celadon_64 -e BOOT_ARCH=efi -e LKBIN_DIR=/root/evmm/"
   - name: "celadon_64 (CLANG)"
     env: EVMM_BUILD_TARGET="-e TRUSTY_REF_TARGET=celadon_64 -e BOOT_ARCH=efi -e LKBIN_DIR=/root/evmm/ -e CLANG_BINDIR=/usr/bin"

install: true

script:
   - if [ ! -f lk.elf ]; then wget https://github.com/YadongQi/ikgt-core/releases/download/v0.1_with_lk/lk.elf; fi
   - docker run -v $PWD:/root/evmm ${EVMM_BUILD_TARGET} ${EVMM_COMPILER} ${OS_TESTED_UBUNTU} /bin/bash -c "make clean && make -j$(nproc)"
