sudo: required

language: c

env:
   global:
      - OS_TESTED_UBUNTU="ubuntu16.04"

services:
   - docker

before_install:
   - docker build -t ${OS_TESTED_UBUNTU} -f .travis-dockerfiles/Dockerfile.${OS_TESTED_UBUNTU} .
   - docker images

install: true

script:
   - docker run -v $PWD:/root/evmm ${OS_TESTED_UBUNTU} /bin/bash -c "export TARGET_PRODUCT=gordon_peak && export BOOTLOADER=abl && make clean && make"
