sudo: required

language: c

env:
   global:
      - OS_TESTED_UBUNTU_1604="ubuntu16.04"
      - OS_TESTED_UBUNTU_1804="ubuntu18.04"

services:
   - docker

before_install:
   - docker build -t ${OS_TESTED_UBUNTU_1604} -f .travis-dockerfiles/Dockerfile.${OS_TESTED_UBUNTU_1604} .
   - docker build -t ${OS_TESTED_UBUNTU_1804} -f .travis-dockerfiles/Dockerfile.${OS_TESTED_UBUNTU_1804} .
   - docker images

install: true

script:
   - docker run -v $PWD:/root/evmm ${OS_TESTED_UBUNTU_1604} /bin/bash -c "export TARGET_PRODUCT=gordon_peak && export BOOTLOADER=abl && make clean && make"
   - docker run -v $PWD:/root/evmm ${OS_TESTED_UBUNTU_1804} /bin/bash -c "export TARGET_PRODUCT=gordon_peak && export BOOTLOADER=abl && make clean && make"
