# Build container based on Ubuntu 18.04.3
FROM ubuntu:19.04

# Install dependencies.
RUN apt-get update \
    && apt-get install -y gcc make vim git clang lld \
    && apt-get clean

WORKDIR /root/evmm

CMD ["/bin/bash"]
